//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatronesDeDiseño
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patrones
    {
        public int IdNombrePatron { get; set; }
        public string NombrePatron { get; set; }
        public Nullable<int> IdAutorPatron { get; set; }
        public Nullable<int> IdLana { get; set; }
        public Nullable<int> IdPrendas { get; set; }
        public Nullable<int> IdRevistas { get; set; }
        public Nullable<int> IdTiposCaract { get; set; }
        public Nullable<int> IdTiposdeTejer { get; set; }
        public byte[] Patron { get; set; }
    
        public virtual AutorPatron AutorPatron { get; set; }
        public virtual Lanas Lanas { get; set; }
        public virtual Prendas Prendas { get; set; }
        public virtual Revistas Revistas { get; set; }
        public virtual TiposCaracteristicas TiposCaracteristicas { get; set; }
        public virtual TiposDeTejer TiposDeTejer { get; set; }
    }
}
